@startuml

skinparam linetype ortho

/' Back End '/
package "Kernel" #DDDDDD {

  Abstract Component {
      #fatherNode : Component
      #id : String
      #name : String
      #description: String
      #startTime: LocalDateTime
      #finishTime: LocalDateTime
      #toJson() : JSONObject
      #getDuration() : Duration
      #print(indentation : int) : void
      #Component(fatherNode: Project, name : String, description : String)
      #Component(jsonObject: JSONObject)
      #toJsonComponent(jsonObject: JSONObject) : JSONObject
      #updateStartTime(time : LocalDateTime) : void
      #updateFinishTime(time : LocalDateTime) : void
      #generateUUID() : String
      +generateCustomIndentation(indentation : int) : String
      +getName() : String
      +getStartTime() : LocalDateTime
      +getFinishTime() : LocalDateTime
      +setFinishTime(time : LocalDateTime) : void
      +setStartTime(time : LocalDateTime) : void
      +printComponentTimes() : void



  }

  class Project {
     -_children: list<Component>
     +Project(fatherNode: Project, name : String, description : String)
     +Project(jsonObject: JSONObject) : void
     +addComponent(Component : ProjectComponent) : void
     +toJson(): JSONObject
     +getDuration() : Duration
     +print(indentation : int)
     +getComponentById(id : String) : Component
     +RemoveComponent(id : String) : boolean
     -generateChildrenFromJson(jsonArray :JSONArray) : void
     -generateTaskFromJson(childJson : JSONObject) : void
     -generateProjectFromJson(childJson : JSONObject) : void
     -childrenTomJson() : JSONArray
  }

  class Task {
    -_intervals: list<Interval>
    -_runningInterval : Interval
    +Task(fatherNode: Project, name : String, description : String)
    +Task(jsonObject: JSONObject)
    +toJson(): JSONObject
    +addInterval(interval : Interval) : void
    +startTask() : void
    +finishTask() : void
    +getDuration() : Duration
    +print(indentation : int) : void
    +printTimes() : void
    -intervalsToJson(): JSONArray
    -loadIntervalsFromJson(jsonArray :JSONArray) : void
    -startObservingClock() : void
    -stopObservingClock() : void
  }

  class Interval {
    -_start : LocalDateTime
    -_end : LocalDateTime
    -_fatherTask : Task
    +Interval(task : Task)
    +Interval(jsonObject: JSONObject)
    +toJson():JSONObject
    +getDuration() : Duration
    +update(obs : Observable, arg : Object)
    +printTimes() : void
    +printIntervalTimes() : void
  }

  class Clock{
  -_timer: Timer
  -_clock: Clock
  -_cancelTimer: boolean
  + {static} getInstance() : Clock
  +startClock() : void
  +stopClock() : void
  -tick() : void
  -stopTimer() : void
  }

  class JsonReader {
    + {static} readJson(fileName : String) : JSONObject
    - {static} readJsonFile(fileName : String) : String
    - {static} readFile(file : File) : String
  }

  class JsonWriter {
    + {static} saveJson(json:JSONObject) : void
    + {static} saveJsonPrettier(json:JSONObject) : void
  }

  package "java.util"
  {
      abstract Observable {
        +AddObserver(o:Observer) : void
        +DeleteObserver(o:Observer) : void
        +DeleteObservers() : void
        #SetChanged() : void
        +HasChanged() : bool
        #ClearChanged() : void
        +NotifyObservers(arg:object) : void
      }
      interface Observer
      {
           +void Update(observable : Observable, arg: object )
      }
      Observable "0..N" *--> "1" Observer:ObserverList
  }

}

/' Relationship '/
  Task -right-|> Component
  Component <|-- Project
  Component "N" --o "1" Project : Children
  Task "1" o-- "0..N" Interval
  Interval ..|> Observer
  Clock --|> Observable

@enduml
